### ISSUE TITLE
添加图片url

### ISSUE THREAD

**Issue by Tsy1** [itning/sports-mall-server#1]
图片地址怎么添加呢，是复制百度上某图片的连接地址，还是本地文件路径，谢谢作者大大告知

**Comment by itning** [comment]
![https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111165033.jpg](https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111165033.jpg)

网络上任意图片地址

**Comment by Tsy1** [comment]
但是添加就一直转圈，也不发送请求

**Comment by itning** [comment]
> 但是添加就一直转圈，也不发送请求

你添加的地址是什么，发下

**Comment by Tsy1** [comment]
https://iknow-pic.cdn.bcebos.com/bba1cd11728b4710af276bdbcdcec3fdfc032398

**Comment by itning** [comment]
**我这边看了下，没有复现出来，你那边怎么添加的?**

![](https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111170149.jpg)

![](https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111170206.jpg)

![](https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111170333.jpg)

![](https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111170413.jpg)

![](https://raw.githubusercontent.com/itning/FilePool/master/images/Dingtalk_20210111170520.jpg)

**Comment by Tsy1** [comment]
就创建分类，然后商品管理一个一个输入，商品url和轮播Url用的刚发的这个地址，可能是我项目的问题

**Comment by itning** [comment]
> 就创建分类，然后商品管理一个一个输入，商品url和轮播Url用的刚发的这个地址，可能是我项目的问题

浏览器 按F12打开开发者工具 看下控制台是否有报错？

图片地址 是否正确填充了？

**Comment by itning** [comment]
![F12](https://raw.githubusercontent.com/itning/FilePool/84188cab69ba67955c19e1dd98720ce3c83d41af/images/Dingtalk_20210111171354.jpg)

**Comment by Tsy1** [comment]
图片填充完整了，估计是前端项目vue的什么组件没导入，谢谢你

**Comment by itning** [comment]
> 图片填充完整了，估计是前端项目vue的什么组件没导入，谢谢你

没事
