### ISSUE TITLE
Issue with weak JWT signing key

### ISSUE THREAD

**Issue by luchua-bc** [itning/sports-mall-server#2]
Hi @itning,

Thanks for sharing the project and it's a nice one.

I noticed one issue - in the program <code>com/sport/sportsmallserver/util/JwtUtils.java</code>, it uses a short password (6 characters) as the signing key of JWT signatures.

JWT Best Practices require human-memorizable passwords MUST NOT be directly used as the key to a keyed-MAC algorithm such as “HS256”. RFC 7518 recommends to use a password that is as large as (or larger than) the derived key length in JSON web algorithms. Common JWT signature algorithms are HS256, HS384, and HS512.

And jjwt versions 0.10.0+ enforce this constraint. Please consider to replace it with a strong key, preferably stored in an environment variable or a vault, and build with a newer jjwt version.

Thanks,
@luchua-bc

**Comment by itning** [comment]
Thank you for your suggestion, I already understand and pay attention to this issue. Because this project is a demo project and will not be used in a production environment, it will not be changed for the time being. Finally, thank you again for your suggestions.
